id     = "PARALLEL"
name   = "Parallel"

[[option]]
  name       = "computePartitions"
  category   = "expert"
  long       = "compute-partitions=N"
  type       = "uint64_t"
  default    = "0"
  help       = "make n partitions. n <2 disables computing partitions entirely"

[[option]]
  name       = "partitionTimeLimit"
  category   = "expert"
  long       = "partition-tlimit=N"
  type       = "uint64_t"
  default    = "60"
  help       = "time limit for partitioning in seconds"

[[option]]
  name       = "partitionStartTime"
  category   = "expert"
  long       = "partition-start-time=N"
  type       = "uint64_t"
  default    = "30"
  help       = "time to start creating partitions in seconds"

[[option]]
  name       = "partitionTimeInterval"
  category   = "expert"
  long       = "partition-time-interval=N"
  type       = "double"
  default    = "1.0"
  help       = "time to wait between DNC partitions"

[[option]]
  name       = "checksBeforePartitioning"
  category   = "expert"
  long       = "checks-before-partition=N"
  type       = "uint64_t"
  default    = "1"
  help       = "number of standard or full effort checks until partitioning"

[[option]]
  name       = "partitionWhen"
  category   = "expert"
  long       = "partition-when=MODE"
  type       = "PartitionWhenMode"
  default    = "TLIMIT"
  help       = "choose when to partition"
  help_mode  = "PartitionWhen modes."
[[option.mode.TLIMIT]]
  name = "tlimit"
  help = "Partition when the time limit is exceeded."
[[option.mode.CLIMIT]]
  name = "climit"
  help = "Partition when number of checks is exceeded."
[[option.mode.CLIMIT_TBACKUP]]
  name = "climit-tbackup"
  help = "Partition when number of checks is exceeded, unless the time limit is exceeded first."
[[option.mode.TLIMIT_CBACKUP]]
  name = "tlimit-cbackup"
  help = "Partition when time limit is exceeded, unless the check limit is exceeded first."

[[option]]
  name       = "checksBetweenPartitions"
  category   = "expert"
  long       = "checks-between-partitions=N"
  type       = "uint64_t"
  default    = "1"
  help       = "number of checks between partitions"

[[option]]
  name       = "partitionConflictSize"
  category   = "expert"
  long       = "partition-conflict-size=N"
  type       = "uint64_t"
  default    = "0"
  help       = "number of literals in a cube; if no partition size is set, then the partition conflict size is chosen to be log2(number of requested partitions)"

[[option]]
  name       = "partitionStrategy"
  category   = "expert"
  long       = "partition-strategy=MODE"
  type       = "PartitionMode"
  default    = "HEAP_CUBES"
  help       = "choose partition strategy mode"
  help_mode  = "Partition strategy modes."
[[option.mode.DECISION_DNCS]]
  name = "decision-dncs"
  help = "For 4 partitions, creates cubes C1, !C1 & C2, !C1 & !C2 & C3, !C1 & !C2 & !C3, from decisions"
[[option.mode.HEAP_DNCS]]
  name = "heap-dncs"
  help = "For 4 partitions, creates cubes C1, !C1 & C2, !C1 & !C2 & C3, !C1 & !C2 & !C3, from heap"
[[option.mode.LEMMA_DNCS]]
  name = "lemma-dncs"
  help = "For 4 partitions, creates cubes C1, !C1 & C2, !C1 & !C2 & C3, !C1 & !C2 & !C3, from lemmas"
[[option.mode.DECISION_CUBES]]
  name = "decision-cubes"
  help = "Creates mutually exclusive cubes from the decisions in the SAT solver."
[[option.mode.HEAP_CUBES]]
  name = "heap-cubes"
  help = "Creates mutually exclusive cubes from the order heap in the SAT solver."
[[option.mode.LEMMA_CUBES]]
  name = "lemma-cubes"
  help = "Creates mutually exclusive cubes from the lemmas sent to the SAT solver."

[[option]]
  name       = "partitionCheck"
  alias      = ["check"]
  category   = "expert"
  long       = "partition-check=MODE"
  type       = "CheckMode"
  default    = "STANDARD"
  help       = "select whether partitioning happens at full or standard check"
  help_mode  = "Partition check modes."
[[option.mode.STANDARD]]
  name = "standard"
  help = "create partitions at standard checks"
[[option.mode.FULL]]
  name = "full"
  help = "create partitions at full checks"

[[option]]
  name       = "partitionsOut"
  alias      = ["partitions-out"]
  category   = "expert"
  long       = "write-partitions-to=output"
  type       = "ManagedOut"
  default    = "ManagedOut()"
  includes   = ["<iostream>", "options/managed_streams.h"]
  help       = "set the output channel for writing partitions"

[[option]]
  name       = "appendLearnedLiteralsToCubes"
  category   = "expert"
  long       = "append-learned-literals-to-cubes"
  type       = "bool"
  default    = "false"
  help       = "emit learned literals with the cubes"

[[option]]
  name       = "randomPartitioning"
  category   = "expert"
  long       = "random-partitioning"
  type       = "bool"
  default    = "false"
  help       = "create random partitions"

[[option]]
  name       = "takeWhatYouCan"
  category   = "expert"
  long       = "take-what-you-can"
  type       = "bool"
  default    = "false"
  help       = "ignore conflict size to prioritize fast partitioning"

[[option]]
  name       = "prioritizeLiterals"
  category   = "expert"
  long       = "prioritize-literals"
  type       = "bool"
  default    = "false"
  help       = "prioritize literals with our input/noninput/skolem/noskolem heuristic"

[[option]]
  name       = "useBackupCubes"
  category   = "expert"
  long       = "use-backup-cubes"
  type       = "bool"
  default    = "false"
  help       = "if DNC strategy does not create enough partitions, cube on what's available"

[[option]]
  name       = "useRecentLemmas"
  category   = "expert"
  long       = "use-recent-lemmas"
  type       = "bool"
  default    = "false"
  help       = "When using lemmas (whether for DNC or cube strategy), use most recent rather than most frequent"

[[option]]
  name       = "clearAllLemmas"
  category   = "expert"
  long       = "clear-all-lemmas"
  type       = "bool"
  default    = "false"
  help       = "When using lemmas for DNC strategy, clear all lemmas"

[[option]]
  name       = "useTail"
  category   = "expert"
  long       = "use-tail"
  type       = "bool"
  default    = "false"
  help       = "Option to use the last n literals instead of the first n for partitioning"

[[option]]
  name       = "progressiveDNCs"
  category   = "expert"
  long       = "progressive-dncs"
  type       = "bool"
  default    = "false"
  help       = "When using DNC strategy, change number of literals in successive partitions"

[[option]]
  name       = "maxConflictSize"
  category   = "expert"
  long       = "max-conflict-size=N"
  type       = "uint64_t"
  default    = "3"
  help       = "Maximum number of literals to use when doing progressive DNC"

[[option]]
  name       = "minConflictSize"
  category   = "expert"
  long       = "min-conflict-size=N"
  type       = "uint64_t"
  default    = "1"
  help       = "Minimum number of literals to use when doing progressive DNC"

[[option]]
  name       = "conflictSizeInterval"
  category   = "expert"
  long       = "conflict-size-interval=N"
  type       = "uint64_t"
  default    = "1"
  help       = "Difference in the number of literals when doing progressive DNC"

